# -*- coding: utf-8 -*-
"""final project largest cardboard .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XXso3VpFBFu5mKtm0J3ZTnR6WZs-eQuf

## Data Preparation
"""

# Run this cell to mount your Google Drive.
from google.colab import drive
drive.mount('drive')

import numpy as np

read_in_array = np.loadtxt('/content/drive/MyDrive/Physics 4AL/final project biggest cardboard - Sheet1.csv', delimiter = ',', skiprows = 1)

# Get the zeroeth column
time_data_array = read_in_array[:, 0]

# convert from ms to s
time_data_array = time_data_array/1000

# Get the fourth column, the second and third column in the data are accelerations from the accelerometer sensor
position_data_array = read_in_array[:, 1]

# convert from mm to m
position_data_array=(position_data_array/100)-.27

# Test plot
import matplotlib.pyplot as plt
plt.plot(time_data_array, position_data_array)
plt.xlabel('Time (s)')
plt.ylabel('Distance (m)')

# Plot vs index to see where we should cut off the data

plt.plot(position_data_array)
plt.vlines(73, -.16, .16, color = 'red')
plt.vlines(120, -.16, .16, color = 'red')
#plt.ylim([-.16, .16])
plt.ylabel('Amplitude')
plt.xlabel('Index')

position_data_array_clip1 = position_data_array[90:125]#125
time_data_array_clip1 = time_data_array[90:125]
time_data_array_clip1 = time_data_array_clip1 - time_data_array_clip1[0]

plt.plot(time_data_array_clip1, position_data_array_clip1)
plt.vlines(.4, -.1, .1, color = 'red', linestyle = 'dashed')
plt.vlines(1.18, -.1, .1, color = 'red', linestyle = 'dashed')

plt.hlines(0.0,0, 1.27,  color = 'blue', linestyle = 'dashed')
plt.hlines(.048,0, 1.27,  color = 'blue', linestyle = 'dashed')
#plt.xlim([0, 1.75])
#plt.ylim([.08, 0.21])
plt.xlabel('Time (ms)')
plt.ylabel('Amplitude')

from scipy.optimize import least_squares

guess_amplitude = .05
guess_omega = 2 * np.pi / (1.18 - .4)
guess_offset = 0
guess_phi = 0.2

guess_parameters = [guess_amplitude, guess_omega, guess_offset, guess_phi]

def cos_fit_fun_1(parameters, time):
  a = parameters[0]
  omega = parameters[1]
  offset = parameters[2]
  phi = parameters[3]
  y = a * np.cos(omega * time + phi) + offset
  return y

def get_residuals(parameters, position_data, time_data):
  theoretical_function = cos_fit_fun_1(parameters, time_data)
  residuals = np.abs(theoretical_function - position_data)
  return residuals

theoretical_guess_function = cos_fit_fun_1(guess_parameters, time_data_array_clip1)
plt.plot(time_data_array_clip1, theoretical_guess_function, label='Guess function')
plt.plot(time_data_array_clip1, position_data_array_clip1, label = 'Data')
plt.legend()
plt.xlabel('Time (s)')
plt.ylabel('Position (m)')

from scipy.optimize import least_squares

res_lsq = least_squares(get_residuals, guess_parameters, args=(position_data_array_clip1,time_data_array_clip1))

best_parameters = res_lsq['x']
fitted_function = cos_fit_fun_1(best_parameters, time_data_array_clip1)
plt.plot(time_data_array_clip1, position_data_array_clip1, label = 'Data')
plt.plot(time_data_array_clip1, fitted_function, color = 'red', label='Best fit function')
print('Best Amplitude: ' + str(best_parameters[0]))
print('Best Omega: ' + str(best_parameters[1]))
print('Best offset: ' + str(best_parameters[2]))
print('Best Phi: ' + str(best_parameters[3]))
plt.legend()
plt.xlabel('Time (s)')
plt.ylabel('Position (m)')

# Plot vs index to see where we should cut off the data

plt.plot(position_data_array)
plt.vlines(90, -.1, .1, color = 'red')
plt.vlines(250, -.1, .1, color = 'red')
#plt.ylim()

position_data_array_clip2 = position_data_array[90:250]
time_data_array_clip2 = time_data_array[90:250]
time_data_array_clip2 = time_data_array_clip2 - time_data_array_clip2[0]

guess_parameters = best_parameters
theoretical_guess_function = cos_fit_fun_1(guess_parameters, time_data_array_clip2)
plt.plot(time_data_array_clip2, position_data_array_clip2, alpha = 0.8, label = 'Data')
plt.plot(time_data_array_clip2, theoretical_guess_function, color='orange', label = 'Prediction 1 ')
plt.legend()
plt.xlabel('Time (s)')
plt.ylabel('Position (m)')

guess_parameters = best_parameters
res_lsq = least_squares(get_residuals, guess_parameters, args=(position_data_array_clip2,time_data_array_clip2))

best_parameters = res_lsq['x']
fitted_function = cos_fit_fun_1(best_parameters, time_data_array_clip2)
plt.plot(time_data_array_clip2, position_data_array_clip2, alpha = 0.8, label='Data')
plt.plot(time_data_array_clip2, fitted_function, color = 'orange', label='Prediction 2')
print('Best Amplitude: ' + str(best_parameters[0]))
print('Best Omega: ' + str(best_parameters[1]))
print('Best offset: ' + str(best_parameters[2]))
print('Best Phi: ' + str(best_parameters[3]))
plt.legend()
plt.xlabel('Time (s)')
plt.ylabel('Position (m)')

def cos_fit_fun_damped(parameters, time):
  a = parameters[0]
  omega = parameters[1]
  offset = parameters[2]
  phi = parameters[3]
  tau = parameters[4]
  y = a * np.cos(omega * time + phi) * np.exp(-time / tau) + offset
  return y

def get_residuals(parameters, position_data, time_data):
  theoretical_function = cos_fit_fun_damped(parameters, time_data)
  residuals = np.abs(theoretical_function - position_data)
  return residuals

"""
$e^{-t / \tau} = \frac{y(t)}{y(0)}$



$\tau = \frac{t}{\ln\left( \frac{y(0)}{y(t)} \right)}$
"""

best_parameters = res_lsq['x']
plt.plot(time_data_array_clip2, position_data_array_clip2)

# To see the offset
plt.hlines(best_parameters[2],-0, 6, color = 'red', linestyle = 'dashed')
print('Best offset: ' + str(best_parameters[2]))

# To see the peak of the first cycle and the 11th cycle
plt.hlines([.05, .03], 0, 6, color = 'green', linestyle = 'dashed')
plt.vlines(1.63,-.1,.1)
plt.xlabel('Time (s)')
plt.ylabel('Position (m)')

"""$y(t = 1.63) \approx 0.03$

$y(t = 0) \approx .05$

Subtracting off the offset

$y_{offset}(t=0) \approx .02$


$y_{offset}(t=1.63) \approx 0.0$

$ \tau = \frac{t}{ \ln\left( \frac{ y(0) }{ y(t)}\right) } $



"""

def find_tau(t, y_t, y_0):
  nom = t
  denom = np.log(y_0 / y_t)
  tau = nom / denom
  print('Tau is ' + str(tau))

find_tau(1.63, .000001, .02)

guess_parameters = np.append(best_parameters, 2.31)
print(guess_parameters)

theoretical_guess_function = cos_fit_fun_damped(guess_parameters, time_data_array_clip2)
plt.plot(time_data_array_clip2, position_data_array_clip2, color = 'red', alpha = 0.8, label = 'Data')
plt.plot(time_data_array_clip2, theoretical_guess_function, color = 'blue', label = 'Damped guess function')
plt.legend()
plt.xlabel('Time (s)')
plt.ylabel('Position (m)')

def get_residuals(parameters, position_data, time_data):
  theoretical_function = cos_fit_fun_damped(parameters, time_data)
  residuals = np.abs(theoretical_function - position_data)
  return residuals

res_lsq = least_squares(get_residuals, guess_parameters, args=(position_data_array_clip2,time_data_array_clip2))
best_parameters = res_lsq['x']
fitted_function = cos_fit_fun_damped(best_parameters, time_data_array_clip2)
plt.plot(time_data_array_clip2, position_data_array_clip2, color='red',alpha = 0.8, label='Position Data')
plt.plot(time_data_array_clip2, fitted_function, color = 'blue', label = 'Damped best function' )
print('Best Amplitude: ' + str(best_parameters[0]))
print('Best Omega: ' + str(best_parameters[1]))
print('Best offset: ' + str(best_parameters[2]))
print('Best Phi: ' + str(best_parameters[3]))
print('Best Tau: ' + str(best_parameters[4]))
plt.legend()
plt.xlabel('Time (s)')
plt.ylabel('Position (m)')
plt.title('Position Best Fit vs Position from Data')

# Get the zeroeth column
time_data_array = read_in_array[:, 0]

# convert from ms to s
time_data_array = time_data_array/1000

# Get the fourth column, the second and third column in the data are accelerations from the accelerometer sensor
acceleration_data_array = read_in_array[:, 2]

# convert from cm/ms^2 to m/s^2
acceleration_data_array=acceleration_data_array/10000

import matplotlib.pyplot as plt
plt.plot(time_data_array, acceleration_data_array)
plt.xlabel('Time (s)')
plt.ylabel('Acceleration (m/s^2)')

plt.plot(acceleration_data_array)
plt.vlines(65, -1, .7, color = 'red')
plt.vlines(200, -1, .7, color = 'red')
plt.ylim([-1, .7])

plt.ylabel('Accleration')
plt.xlabel('Index')

acceleration_data_array_clip1 = acceleration_data_array[89:200]
time_data_array_clip1 = time_data_array[89:200]
time_data_array_clip1 = time_data_array_clip1 - time_data_array_clip1[0]

plt.plot(time_data_array_clip1, acceleration_data_array_clip1)
plt.vlines(0, -.7, .7, color = 'red', linestyle = 'dashed')
plt.vlines(1.22, -.7, .7, color = 'red', linestyle = 'dashed')

plt.hlines(-1.23,0, 2,  color = 'blue', linestyle = 'dashed')
plt.hlines(-1.0,0, 2,  color = 'blue', linestyle = 'dashed')
#plt.xlim([0, 1.75])
#plt.ylim([.08, 0.21])
plt.xlabel('Time (ms)')
plt.ylabel('Amplitude')

from scipy.optimize import least_squares

guess_amplitude = .033
guess_omega = 2 * np.pi / (1.7 - .59)
guess_offset = -1.23
guess_phi = 0.2

guess_parameters = [guess_amplitude, guess_omega, guess_offset, guess_phi]

def cos_fit_fun_1(parameters, time):
  a = parameters[0]
  omega = parameters[1]
  offset = parameters[2]
  phi = parameters[3]
  y = -1*a * omega* np.sin(omega * time + phi) + offset
  return y

def get_residuals(parameters, position_data, time_data):
  theoretical_function = cos_fit_fun_1(parameters, time_data)
  residuals = np.abs(theoretical_function - position_data)
  return residuals

theoretical_guess_function = cos_fit_fun_1(guess_parameters, time_data_array_clip1)
plt.plot(time_data_array_clip1, theoretical_guess_function, label='Guess function')
plt.plot(time_data_array_clip1, acceleration_data_array_clip1, label = 'Data')
plt.legend()
plt.xlabel('Time (s)')
plt.ylabel('Acceleration (m/s^2)')

from scipy.optimize import least_squares

res_lsq = least_squares(get_residuals, guess_parameters, args=(acceleration_data_array_clip1,time_data_array_clip1))

best_parameters = res_lsq['x']
fitted_function = cos_fit_fun_1(best_parameters, time_data_array_clip1)
plt.plot(time_data_array_clip1, acceleration_data_array_clip1, label = 'Data')
plt.plot(time_data_array_clip1, fitted_function, color = 'red', label='Best fit function')
print('Best Amplitude: ' + str(best_parameters[0]))
print('Best Omega: ' + str(best_parameters[1]))
print('Best offset: ' + str(best_parameters[2]))
print('Best Phi: ' + str(best_parameters[3]))
plt.legend()
plt.xlabel('Time (s)')
plt.ylabel('Acceleration (m.s^2)')

# Plot vs index to see where we should cut off the data

plt.plot(acceleration_data_array)
plt.vlines(82, -1.6, -1.0, color = 'red')
plt.vlines(240, -1.6, -1.0, color = 'red')
#plt.ylim()

acceleration_data_array_clip2 = acceleration_data_array[83:]
time_data_array_clip2 = time_data_array[83:]
time_data_array_clip2 = time_data_array_clip2 - time_data_array_clip2[0]

guess_parameters = best_parameters
theoretical_guess_function = cos_fit_fun_1(guess_parameters, time_data_array_clip2)
plt.plot(time_data_array_clip2, acceleration_data_array_clip2, alpha = 0.8, label = 'Data')
plt.plot(time_data_array_clip2, theoretical_guess_function, color='orange', label = 'Prediction 1 ')
plt.legend()
plt.xlabel('Time (s)')
plt.ylabel('Position (m)')

guess_parameters = best_parameters
res_lsq = least_squares(get_residuals, guess_parameters, args=(acceleration_data_array_clip2,time_data_array_clip2))

best_parameters = res_lsq['x']
fitted_function = cos_fit_fun_1(best_parameters, time_data_array_clip2)
plt.plot(time_data_array_clip2, acceleration_data_array_clip2, alpha = 0.8, label='Data')
plt.plot(time_data_array_clip2, fitted_function, color = 'orange', label='Prediction 2')
print('Best Amplitude: ' + str(best_parameters[0]))
print('Best Omega: ' + str(best_parameters[1]))
print('Best offset: ' + str(best_parameters[2]))
print('Best Phi: ' + str(best_parameters[3]))
plt.legend()
plt.xlabel('Time (s)')
plt.ylabel('Acceleration (m/s^2)')

#y = (a *  np.exp(-time / tau) *(2*tau*omega*np.sin(omega*time + phi))+(1-(tau**2)*(omega**2)*np.cos(omega*time+phi))/tau**2  + offset

def cos_fit_fun_damped(parameters, time):
  a = parameters[0]
  omega = parameters[1]
  offset = parameters[2]
  phi = parameters[3]
  tau = parameters[4]
  y = ((a *  np.exp(-time / tau) *((2*tau*omega*np.sin(omega*time + phi))+(1-(tau**2)*(omega**2))*np.cos(omega*time+phi))/tau**2 )) + offset
  return y

def get_residuals(parameters, acceleration_data, time_data):
  theoretical_function = cos_fit_fun_damped(parameters, time_data)
  residuals = np.abs(theoretical_function - acceleration_data)
  return residuals

best_parameters = res_lsq['x']
plt.plot(time_data_array_clip2, acceleration_data_array_clip2)

# To see the offset
plt.hlines(best_parameters[2],-0, 7, color = 'red', linestyle = 'dashed')
print('Best offset: ' + str(best_parameters[2]))

# To see the peak of the first cycle and the 11th cycle
plt.hlines([-1.1, -1.19], 0, 7, color = 'green', linestyle = 'dashed')
plt.vlines(.76,-1.5,-1.1)
plt.xlabel('Time (s)')
plt.ylabel('Acceleration (m)')

"""$y(t = 3.2) \approx -1.2$

$y(t = 0.76) \approx -1.1$

Subtracting off the offset

$y_{offset}(t=0.76) \approx 0.16$


$y_{offset}(t=3.2) \approx 0.06$

$ \tau = \frac{t}{ \ln\left( \frac{ y(0) }{ y(t)}\right) } $
"""

def find_tau(t, y_t, y_0):
  nom = t
  denom = np.log(y_0 / y_t)
  tau = nom / denom
  print('Tau is ' + str(tau))

find_tau(3.2, 0.06, 0.16)

guess_parameters = np.append(best_parameters, 3.2625)
print(guess_parameters)

theoretical_guess_function = cos_fit_fun_damped(guess_parameters, time_data_array_clip2)
plt.plot(time_data_array_clip2, acceleration_data_array_clip2, color = 'red', alpha = 0.8, label = 'Data')
plt.plot(time_data_array_clip2, theoretical_guess_function, color = 'blue', label = 'Damped guess function')
plt.legend()
plt.xlabel('Time (s)')
plt.ylabel('Acceleration (m/s^2)')

def get_residuals(parameters, acceleration_data, time_data):
  theoretical_function = cos_fit_fun_damped(parameters, time_data)
  residuals = np.abs(theoretical_function - acceleration_data)
  return residuals

res_lsq = least_squares(get_residuals, guess_parameters, args=(acceleration_data_array_clip2,time_data_array_clip2))
best_parameters = res_lsq['x']
fitted_function = cos_fit_fun_damped(best_parameters, time_data_array_clip2)
plt.plot(time_data_array_clip2, acceleration_data_array_clip2, color='red',alpha = 0.8, label='Data')
plt.plot(time_data_array_clip2, fitted_function, color = 'blue', label = 'Damped best function' )
print('Best Amplitude: ' + str(best_parameters[0]))
print('Best Omega: ' + str(best_parameters[1]))
print('Best offset: ' + str(best_parameters[2]))
print('Best Phi: ' + str(best_parameters[3]))
print('Best Tau: ' + str(best_parameters[4]))
plt.legend()
plt.xlabel('Time (s)')
plt.ylabel('Acceleration (m/s^2)')

plt.plot(time_data_array_clip2, acceleration_data_array_clip2+1.26, color='red',alpha = 0.8, label='Accleration from Data')
plt.plot(time_data_array_clip2, fitted_function+1.26, color = 'blue', label = 'Acceleration best function' )

time=time_data_array_clip2
amp=0.05136821
omega=5.4547
offset=0.1437675
phi=-0.16766
tau=2.3078456
accel_from_differentiation= (((amp *  np.exp(-time / tau) *((2*tau*omega*np.sin(omega*time + phi))+(1-(tau**2)*(omega**2))*np.cos(omega*time+phi))/tau**2 )) + offset)/10
plt.plot(time_data_array_clip2, accel_from_differentiation, color='green', label='Acceleration from differentiation of position best fit')
plt.legend()
plt.xlabel('time (sec)')
plt.ylabel('Accelertaion (m/s^2)')
plt.title('all acceleration graphs')