# -*- coding: utf-8 -*-
"""final project 4bl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZaKqlkVrhncP3gBSquPIJK943QKtH8bT
"""

from google.colab import drive
drive.mount('drive')

import numpy as np

hello = np.loadtxt('/content/drive/MyDrive/Physics 4BL/final project/Hello - Sheet1.csv', delimiter = ',')

import matplotlib.pyplot as plt

xarray=np.linspace(1,220,220)

hello1=hello[20:240]
plt.plot((xarray*0.01),hello1, color= 'red')
plt.xlabel('Time (s)')
plt.ylabel("Anolog Light Intesity")
plt.title("Photoresistor Morse Code of 'hello'")

hello = np.loadtxt('/content/drive/MyDrive/Physics 4BL/final project/"Hello World" 20ms delay - Sheet1.csv', delimiter = ',')

xarray=np.linspace(1,485,485)
hello1=hello[35:520]
plt.plot((xarray*0.01),hello1)
plt.xlabel('Time (s)')
plt.ylabel("Anolog Light Intesity")
plt.title("Photoresistor Morse Code of 'hello world'")