# -*- coding: utf-8 -*-
"""Lab 3D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oUB_xp5NLYfFoKAX5ubg0Hr0s6hpMFH6
"""

from google.colab import drive
drive.mount('drive')
import numpy as np
import matplotlib.pyplot as plt

read_in_array = np.loadtxt('/content/drive/MyDrive/Physics 4AL/Copy of phys 4al lab 3a distance vs time - Sheet1-2.csv',delimiter=',')

#best parameters from 3b
x_axis = read_in_array[:,0]
elapsed_time = (x_axis-x_axis[0])/1000
distance=read_in_array[:,1]/100
distance_data_array_clip1 = distance[76:150]

Best_Amplitude= 0.036938503474675956
Best_Omega= 8.79397007815391
Best_offset= 0.6870085434005583
Best_Phi= -0.2774881894988622

#volcity undamped=Acos(wt+phi)
displacement=Best_Amplitude*np.sin(Best_Omega*elapsed_time+Best_Phi)
velocity_undamped=Best_Amplitude*Best_Omega*np.cos(Best_Omega*elapsed_time + Best_Phi)
plt.plot(elapsed_time, velocity_undamped)
plt.xlabel('Time (s)')
plt.ylabel('Velocity (m/s)')
plt.title('Velocity from Undamped Ultrasound Best Fit Function')
plt.hlines(0.33,0,18)
xmax=0.33
plt.plot(elapsed_time,displacement)

velocity_data_array_clip1 = velocity_undamped[76:150]
time_data_array_clip1 = x_axis[76:150]
time_data_array_clip1 = time_data_array_clip1 - time_data_array_clip1[0]
displacement_data_array_clip1 = displacement[76:150]
plt.plot(time_data_array_clip1, velocity_data_array_clip1)
plt.plot(time_data_array_clip1, displacement_data_array_clip1)
plt.xlabel('Time (ms)')
plt.ylabel('Velocity (m/s)')
plt.title('Velocity from Undamped Ultrasound Best Fit Function')

#KE=.5*(m)v^2
m=.224
KE=(1/2)*m*velocity_data_array_clip1**2
plt.plot(time_data_array_clip1,KE)
plt.xlabel('Time (ms)')
plt.ylabel('Kinetic Energy')
plt.title('Kinetic Energy Graph')

k=17.9
PE=(1/2)*k*(displacement_data_array_clip1-0)**2
plt.plot(time_data_array_clip1,PE)
plt.xlabel('Time (ms)')
plt.ylabel('Kinetic Energy')
plt.title('Potential Energy Graph')

plt.plot(time_data_array_clip1,PE,color='blue',label='Potential Energy')
plt.plot(time_data_array_clip1,KE,color='red',label='Kinteic Energy')
E=PE+KE
plt.plot(time_data_array_clip1,E,color='green',label='Total Energy')
plt.xlabel('Time (ms)')
plt.ylabel('Energy (J)')
plt.title('Kineitc, Potential, and Total Energy for Undpamped Oscillations from Best Fit')
plt.legend()

elapsed_time_clip1 = elapsed_time[76:150]
dxdt=np.gradient(distance_data_array_clip1,elapsed_time_clip1 )
plt.plot(elapsed_time_clip1, dxdt)
plt.xlabel('Time (s)')
plt.ylabel('Velocity (m/s)')
plt.title('Numerical Differentiation of Undamped Data')
plt.plot(elapsed_time_clip1,distance_data_array_clip1-0.69)

m=.224
KEthree=(1/2)*m*dxdt**2
plt.plot(elapsed_time_clip1,KEthree,color='red',label='Kinetic Energy')
plt.xlabel('Time (ms)')
plt.ylabel('Energy (J)')
k=17.9
PEthree=(1/2)*k*(distance_data_array_clip1-0.68)**2
plt.plot(elapsed_time_clip1,PEthree,color='blue',label='Potential Energy')
plt.title('Potential Energy Graph')
Ethree=PEthree+KEthree
plt.plot(elapsed_time_clip1,Ethree,color='green',label='Total Energy')
plt.legend()

read_in_array_ = np.loadtxt('/content/drive/MyDrive/Physics 4AL/Lab 3c data - Sheet1.csv', delimiter = ',', skiprows = 1)

time_data_array= read_in_array_[100:150, 0]/1000
distance_damped=read_in_array_[100:150,1]/100

Amplitude= 0.051368210038841226
Omega= 5.454700827839871
offset= 0.14376749857577237
Phi= -0.16765895824381555
Tau= 2.307845591252687

position=Amplitude*np.cos(Omega*time_data_array+Phi)*np.exp(-time_data_array /Tau)
velocity_damped=(-Amplitude*np.exp(-time_data_array /Tau)*(Tau*Omega*np.sin(Omega*time_data_array+Phi)+np.cos(Omega*time_data_array+Phi)))/Tau
plt.plot(time_data_array,velocity_damped)
plt.plot(time_data_array,position)
plt.xlabel('Time (s)')
plt.ylabel('Velocity (m/s)')
plt.title('Velocity from Damped Ultrasound Best Function')

k=17.9
PEtwo=(1/2)*k*(position-0)**2
plt.plot(time_data_array,PEtwo)
plt.xlabel('Time (s)')
plt.ylabel('Potential Energy')
plt.title('Potential Energy Graph')

m=.224
KEtwo=((1/2)*m*velocity_damped**2)
plt.plot(time_data_array,KEtwo)
plt.xlabel('Time (ms)')
plt.ylabel('Kinetic Energy')
plt.title('Kinetic Energy Graph')

plt.plot(time_data_array,PEtwo,color='blue',label='Potential Energy')
plt.plot(time_data_array,KEtwo,color='red',label='Kinteic Energy')
Etwo=PEtwo+KEtwo
plt.plot(time_data_array,Etwo,color='green',label='Total Energy')
plt.xlabel('Time (ms)')
plt.ylabel('Energy (kJ)')
plt.title('Energy for Damped Oscillations from Best Fit')
plt.legend()
Q=(Tau/2)*np.sqrt(Omega**2-(1/Tau**2))
print('The Q factor is '+str(Q))

dxdt2=np.gradient(distance_damped,time_data_array )
plt.plot(time_data_array, dxdt2)
plt.plot(time_data_array,distance_damped-0.15)
plt.xlabel('Time (s)')
plt.ylabel('Velocity (m/s)')
plt.title('Numerical Differentiation of Damped Data')

KEfour=((1/2)*m*(dxdt2**2))
plt.plot(time_data_array,KEfour,color='red',label='Kinetic Energy')
plt.xlabel('Time (ms)')
k=17.9
PEfour=(1/2)*k*((distance_damped-0.15)**2)
plt.plot(time_data_array,PEfour,color='blue',label='Potential Energy')
plt.ylabel('Energy (J)')
plt.title('Energy from Damped Oscillations from Raw Data')
Energy=((1/2)*m*(dxdt2**2))+(1/2)*k*((distance_damped-0.15)**2)
plt.plot(time_data_array,Energy,color='green',label='Total Energy')
plt.legend()